### ISSUE TITLE
Cannot add null value at onPressureUpdated

### ISSUE THREAD

**Issue by oyve** [oyve/signalk-barometer-trend#5]
Happened when turning sensor on/off

 `Error: Cannot add null value at onPressureUpdated (/home/ramsalt/.signalk/node_modules/signalk-barometer-trend/barometer.js:121:30) at Object.handle (/home/ramsalt/.signalk/node_modules/signalk-barometer-trend/barometer.js:62:62) at u.values.forEach (/home/ramsalt/.signalk/node_modules/signalk-barometer-trend/barometer.js:86:46) at Array.forEach (<anonymous>) at deltas.updates.forEach.u (/home/ramsalt/.signalk/node_modules/signalk-barometer-trend/barometer.js:82:18) at Array.forEach (<anonymous>) at Object.onDeltasUpdate (/home/ramsalt/.signalk/node_modules/signalk-barometer-trend/barometer.js:81:20) at app.subscriptionmanager.subscribe.delta (/home/ramsalt/.signalk/node_modules/signalk-barometer-trend/index.js:26:42) at /usr/local/lib/node_modules/signalk-server/node_modules/baconjs/dist/Bacon.js:1048:16 at /usr/local/lib/node_modules/signalk-server/node_modules/baconjs/dist/Bacon.js:463:23 at processAfters (/usr/local/lib/node_modules/signalk-server/node_modules/baconjs/dist/Bacon.js:359:11) at Object.inTransaction (/usr/local/lib/node_modules/signalk-server/node_modules/baconjs/dist/Bacon.js:439:9) at Dispatcher.push (/usr/local/lib/node_modules/signalk-server/node_modules/baconjs/dist/Bacon.js:1214:24) at Object.buffer.push (/usr/local/lib/node_modules/signalk-server/node_modules/baconjs/dist/Bacon.js:2030:21) at Object.flush (/usr/local/lib/node_modules/signalk-server/node_modules/baconjs/dist/Bacon.js:1997:26) at Timeout.<anonymous> (/usr/local/lib/node_modules/signalk-server/node_modules/baconjs/dist/Bacon.js:2014:25) `

**Comment by oyve** [comment]
Closed in release 2.3.0
